version: '3.8'

services:
  blogs-app:
    image: blogs-app
    build:
      context: .
      dockerfile: "Blogs Applications/Dockerfile"
    container_name: blogs-application
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80

  blogs-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: blogs-database
    environment:
      - SA_PASSWORD=YourStrong@Password123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - blogs-data:/var/opt/mssql

volumes:
  blogs-data:

networks:
  blogs-network:
    driver: bridge